---
root_url: https://britgo.org/
temp_dir: /tmp/Succubus
workers:  10
debug_url: xxx
include_urls:
- https://britgo.org/membersarea
login_redirect_url:   https://britgo.org/user/login
class:  BGA
generator:  Hugo
output_dir:  /Users/peter/Temp/Hugo
hugo:
  config:
    baseURL:      https://xxx.yyy/
    title:        Experiment
    languageCode: en-gb
    disableKinds:
    - taxonomy
    - term
    publishDir:   /Users/peter/temp/Hugo_public
    markup:
      goldmark:
        extensions:
          definitionList: true
        renderer:
          unsafe: true
