---
root_url: https://britgo.org/
debug_url: xxx
include_urls:
- https://britgo.org/membersarea
login_redirect_url:   https://britgo.org/user/login
class:  BGA
generator:  Hugo
hugo:
  config:
    baseURL:      https://xxx.yyy/
    title:        Experiment
    languageCode: en-gb
    disableKinds:
    - taxonomy
    - term
    publishDir:   /Users/peter/temp/Hugo_public
    markup:
      goldmark:
        extensions:
          definitionList: true
        renderer:
          unsafe: true
bridgetown:
  config:
    baseURL:      https://alofmethbin.com/experiment
    title:        Experiment
    pagination:
      enabled: true
    collections:
      sections:
        output: true
        relations:
          belongs_to:
            - articles
            - news
      articles:
        output: true
        relations:
          has_many: sections
      news:
        output: true
        relations:
          has_many: sections
  front_matter:
    home:
      layout: home
      paginate:
        collection: posts
        per_page: 10
    posts:
      layout: posts
      paginate:
        collection: posts
        per_page: 10
