---
root_url: https://britgo.org/
debug_url: xxx
include_urls:
- https://britgo.org/membersarea
exclude_urls:
- https://britgo.org/ratings/current
- https://britgo.org/node/6840
- https://britgo.org/admin/structure/types/manage/page
- https://britgo.org/admin/structure/types/manage/club
- https://britgo.org/admin/structure/types/manage/story
- "^https://britgo.org/join/form"
- "^https://britgo.org/user/login"
- https://britgo.org/howtoplaygo
- https://britgo.org/renew
- https://britgo.org/whatisgo
- https://britgo.org/softwarereviews
- https://britgo.org/tournams/welsh-open/tour-entries.html
- https://britgo.org/tournams/welsh-open/welsh-open-form.html
- https://britgo.org/views/news
- https://britgo.org/bchamp/qualifiers
- https://britgo.org/bchamp/qualifiers2020
- https://britgo.org/bchamp/qualifiers2021
- https://britgo.org/bchamp/qualifiers2022
- https://britgo.org/image/tid/6
- https://britgo.org/image/tid/20
- https://britgo.org/image/tid/32
- https://britgo.org/image/tid/53
- https://britgo.org/image/tid/80
- https://britgo.org/image/tid/82
- https://britgo.org/join/pay
- https://britgo.org/junior/youthgonews
- "\\?order="
- "/taxonomy/term/\\d*/feed$"
- https://britgo.org/image
- https://britgo.org/filmography/ http://www.imdb.com/title/tt0367279
- https://britgo.org/gopcres/ http://www.gentgo.be/tetsuki
- https://britgo.org/form/transfer-your-membership
- https://britgo.org/news/views
- https://britgo.org/history/accounts
- https://britgo.org/pubs/stock
- https://britgo.org/council/
- https://britgo.org/tournams/sheffield-uni/sheffield-uni-form.html
- https://britgo.org/tournams/trigantius/trigantius-form.html
- https://britgo.org/tournams/british-open/british-open-form.html
- https://britgo.org/tournams/sheffield-uni/tour-entries.html
- https://britgo.org/web/book
- https://britgo.org/web/management
- https://britgo.org/tournams/british-open/tour-entries.html
- https://britgo.org/tournams/trigantius/tour-entries.html
- https://britgo.org/files/2017/UK Youth Summer Go Camp 2017 entry  form v3.pdf
- https://britgo.org/results/2008/coventry
- https://britgo.org/council/minutes20130616
- https://britgo.org/council/minutes20130708
- https://britgo.org/files/2019/3peaks2019a.jpg
- https://britgo.org/files/2019/3peaks2019b.jpg
- https://britgo.org/files/2019/3peaks2019c.jpg
- https://britgo.org/files/2019/3peaks2019d.jpg
- https://britgo.org/files/2019/3peaks2019e.jpg
- https://britgo.org/files/2019/3peaks2019f.jpg
- https://britgo.org/files/StockExpGo.jpg
- https://britgo.org/general/
- https://britgo.org/views/results/12months
- https://britgo.org/council
- https://britgo.org/covers/covers
- https://britgo.org/junior/internetgo
- https://britgo.org/reports
- https://britgo.org/files/teaching/Reference form Teachers of YPs.pdf
- https://britgo.org/user/password
- https://britgo.org/events/shodan
- https://britgo.org/name/Alistair%20Wall
- https://britgo.org/news/2016/www.sugaranddice.co.uk
- https://britgo.org/results/2008/shrew
- https://britgo.org/results/2009/shrew
- https://britgo.org/taxonomy/term/www.sugaranddice.co.uk
- https://britgo.org/news/enews2
- https://britgo.org/aga-ejournal/
- https://britgo.org/results/2003/msopairs
- https://britgo.org/position/bookseller
- https://britgo.org/rules/
- https://britgo.org/files/images/gogod_shield.thumbnail.jpg
- https://britgo.org/organisers/handbook/handbook.html
- https://britgo.org/results/1998/shrew
- https://britgo.org/taxonomy/term/29?page=6
- "^https://britgo.org/news/enews1a98.*"
- https://britgo.org/news/../results/2002/cornlight
- https://britgo.org/results/2002/bham
login_redirect_url:   https://britgo.org/user/login
class:  BGA
generator:  Hugo
hugo:
  config:
    baseURL:      https://alofmethbin.com/experiment
    title:        Experiment
    languageCode: en-gb
    disableKinds:
    - taxonomy
    - term
    markup:
      goldmark:
        renderer:
          unsafe: true
bridgetown:
  config:
    baseURL:      https://alofmethbin.com/experiment
    title:        Experiment
    pagination:
      enabled: true
    collections:
      sections:
        output: true
        relations:
          belongs_to:
            - articles
            - news
      articles:
        output: true
        relations:
          has_many: sections
      news:
        output: true
        relations:
          has_many: sections
  front_matter:
    home:
      layout: home
      paginate:
        collection: posts
        per_page: 10
    posts:
      layout: posts
      paginate:
        collection: posts
        per_page: 10
url_replace:
- from: "https://britgo.org/pairgo/photos2019 "
  to:   https://britgo.org/pairgo/photos2019
- from: "https://britgo.org/name/Jon Diamond"
  to:   https://britgo.org/positions#honorary
- from: "https://britgo.org/name/Matthew MacFadyen"
  to:   https://britgo.org/bchamp/matthew.html
- from: "https://britgo.org/name/Tony Atkins"
  to:   https://britgo.org/positions#honorary
- from: "https://britgo.org/name/T Mark Hall"
  to:   https://britgo.org/positions#honorary
- from: "https://britgo.org/name/Francis Roads"
  to:   https://britgo.org/positions#honorary
