---
root_url: https://britgo.org/
include_urls:
- https://britgo.org/membersarea
exclude_urls:
- https://britgo.org/ratings/current
- https://britgo.org/node/6840
- https://britgo.org/admin/structure/types/manage/page
- https://britgo.org/admin/structure/types/manage/club
- https://britgo.org/admin/structure/types/manage/story
- "^https://britgo.org/join/form"
- "^https://britgo.org/user/login"
- https://britgo.org/howtoplaygo
- https://britgo.org/renew
- https://britgo.org/whatisgo
- https://britgo.org/softwarereviews
- https://britgo.org/tournams/welsh-open/tour-entries.html
- https://britgo.org/tournams/welsh-open/welsh-open-form.html
- https://britgo.org/views/news
- https://britgo.org/bchamp/qualifiers
- https://britgo.org/bchamp/qualifiers2020
- https://britgo.org/bchamp/qualifiers2021
- https://britgo.org/bchamp/qualifiers2022
login_redirect_url:   https://britgo.org/user/login
class:  BGA
generator:  Hugo
hugo:
  baseURL:      https://alofmethbin.com/experiment
  title:        Experiment
  languageCode: en-gb
  theme:        ananke
url_replace:
- from: "https://britgo.org/pairgo/photos2019 "
  to:   https://britgo.org/pairgo/photos2019
- from: "https://britgo.org/name/Jon Diamond"
  to:   https://britgo.org/positions#honorary
- from: "https://britgo.org/name/Matthew MacFadyen"
  to:   https://britgo.org/bchamp/matthew.html
- from: "https://britgo.org/name/Tony Atkins"
  to:   https://britgo.org/positions#honorary
- from: "https://britgo.org/name/T Mark Hall"
  to:   https://britgo.org/positions#honorary
- from: "https://britgo.org/name/Francis Roads"
  to:   https://britgo.org/positions#honorary
